DROP TABLE CAMPAIGN CASCADE CONSTRAINTS;
CREATE TABLE CAMPAIGN ( 
    id NUMBER UNIQUE NOT NULL, 
    name VARCHAR2(50) NOT NULL, 
    start_date DATE NOT NULL, 
    end_date DATE NOT NULL, 
    description VARCHAR2(400), 
    goal VARCHAR2(100)
);

DROP TABLE DONOR CASCADE CONSTRAINTS;
CREATE TABLE DONOR (
    id NUMBER UNIQUE NOT NULL,
    name VARCHAR2(50) NOT NULL,
    mobile VARCHAR2(20) NOT NULL,
    address_line1 VARCHAR2(50) NOT NULL,
    address_line2 VARCHAR2(50),
    city VARCHAR2(50) NOT NULL,
    governorate VARCHAR2(50) NOT NULL
);

DROP TABLE DONATION CASCADE CONSTRAINTS;
CREATE TABLE DONATION ( 
    value NUMBER NOT NULL,
    donation_type VARCHAR2(20) NOT NULL,
    donation_date DATE NOT NULL,
    campaign_id NUMBER NOT NULL,
    donor_id NUMBER NOT NULL,
    CONSTRAINT DONATION_PK PRIMARY KEY(campaign_id, donor_id, donation_date),
    CONSTRAINT DONATION_CAMPAING_ID_FK FOREIGN KEY(campaign_id) REFERENCES CAMPAIGN(id),
    CONSTRAINT DONATION_DONOR_ID_FK FOREIGN KEY(donor_id) REFERENCES DONOR(id)
);

DROP TABLE BRANCH CASCADE CONSTRAINTS;
CREATE TABLE BRANCH (
    id NUMBER UNIQUE NOT NULL,
    address_line1 VARCHAR2(50) NOT NULL,
    address_line2 VARCHAR2(50),
    city VARCHAR2(50) NOT NULL,
    governorate VARCHAR2(50) NOT NULL
);

DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
CREATE TABLE EMPLOYEE (
    ssn VARCHAR2(30) UNIQUE NOT NULL,
    name VARCHAR2(50) NOT NULL,
    mobile VARCHAR2(20) NOT NULL,
    birth_date DATE,
    gender CHAR(1),
    address_line1 VARCHAR2(50) NOT NULL,
    address_line2 VARCHAR2(50),
    city VARCHAR2(50) NOT NULL,
    governorate VARCHAR2(50) NOT NULL,
    email VARCHAR2(50),
    branch_id NUMBER NOT NULL,
    CONSTRAINT EMPLOYEE_BRANCH_ID_FK FOREIGN KEY(branch_id) REFERENCES BRANCH(id)
);

DROP TABLE PAID_EMPLOYEE CASCADE CONSTRAINTS;
CREATE TABLE PAID_EMPLOYEE (
    employee_ssn VARCHAR2(30) UNIQUE NOT NULL,
    salary NUMBER NOT NULL,
    department_name VARCHAR2(30) NOT NULL,
    CONSTRAINT PAID_EMPLOYEE_EMPLOYEE_SSN_FK FOREIGN KEY(employee_ssn) REFERENCES EMPLOYEE(ssn),
    CONSTRAINT PAID_EMPLOYEE_DN_FK FOREIGN KEY(department_name) REFERENCES DEPARTMENT(name)
);

DROP TABLE VOLUNTEER CASCADE CONSTRAINTS;
CREATE TABLE VOLUNTEER (
    employee_ssn VARCHAR2(30) UNIQUE NOT NULL,
    is_currently_volunteering NUMBER(1,0) NOT NULL,
    CONSTRAINT VOLUNTEER_EMPLOYEE_SSN_FK FOREIGN KEY(employee_ssn) REFERENCES EMPLOYEE(ssn)
);

DROP TABLE CAMPAIGN_VOLUNTEER CASCADE CONSTRAINTS;
CREATE TABLE CAMPAIGN_VOLUNTEER (
    campaign_id NUMBER NOT NULL,
    volunteer_ssn VARCHAR2(30) NOT NULL,
    description VARCHAR2(100),
    CONSTRAINT CAMPAIGN_VOLUNTEER_PK PRIMARY KEY(campaign_id, volunteer_ssn),
    CONSTRAINT CAMPAIGN_CAMPAIGN_ID_FK FOREIGN KEY(campaign_id) REFERENCES CAMPAIGN(id),
    CONSTRAINT CAMPAIGN_VOLUNTEER_SSN_FK FOREIGN KEY(volunteer_ssn) REFERENCES VOLUNTEER(employee_ssn)
);

DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
CREATE TABLE DEPARTMENT (
    name VARCHAR2(30) UNIQUE NOT NULL
);